// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: machine-status.proto

package status

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MachineStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string  `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HostUuid string  `protobuf:"bytes,2,opt,name=hostUuid,proto3" json:"hostUuid,omitempty"`
	Load     *Load   `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	Memory   *Memory `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Docker   *Docker `protobuf:"bytes,5,opt,name=docker,proto3" json:"docker,omitempty"`
	Disk     []*Disk `protobuf:"bytes,6,rep,name=disk,proto3" json:"disk,omitempty"`
}

func (x *MachineStatus) Reset() {
	*x = MachineStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatus) ProtoMessage() {}

func (x *MachineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_machine_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatus.ProtoReflect.Descriptor instead.
func (*MachineStatus) Descriptor() ([]byte, []int) {
	return file_machine_status_proto_rawDescGZIP(), []int{0}
}

func (x *MachineStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineStatus) GetHostUuid() string {
	if x != nil {
		return x.HostUuid
	}
	return ""
}

func (x *MachineStatus) GetLoad() *Load {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *MachineStatus) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MachineStatus) GetDocker() *Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *MachineStatus) GetDisk() []*Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type Load struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneMinLoad     float32 `protobuf:"fixed32,1,opt,name=oneMinLoad,proto3" json:"oneMinLoad,omitempty"`
	FiveMinLoad    float32 `protobuf:"fixed32,2,opt,name=fiveMinLoad,proto3" json:"fiveMinLoad,omitempty"`
	FifteenMinLoad float32 `protobuf:"fixed32,3,opt,name=fifteenMinLoad,proto3" json:"fifteenMinLoad,omitempty"`
	ProcTotal      int32   `protobuf:"varint,4,opt,name=procTotal,proto3" json:"procTotal,omitempty"`
	ProcRunning    int32   `protobuf:"varint,5,opt,name=procRunning,proto3" json:"procRunning,omitempty"`
	ProcBlocked    int32   `protobuf:"varint,6,opt,name=procBlocked,proto3" json:"procBlocked,omitempty"`
}

func (x *Load) Reset() {
	*x = Load{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Load) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load) ProtoMessage() {}

func (x *Load) ProtoReflect() protoreflect.Message {
	mi := &file_machine_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load.ProtoReflect.Descriptor instead.
func (*Load) Descriptor() ([]byte, []int) {
	return file_machine_status_proto_rawDescGZIP(), []int{1}
}

func (x *Load) GetOneMinLoad() float32 {
	if x != nil {
		return x.OneMinLoad
	}
	return 0
}

func (x *Load) GetFiveMinLoad() float32 {
	if x != nil {
		return x.FiveMinLoad
	}
	return 0
}

func (x *Load) GetFifteenMinLoad() float32 {
	if x != nil {
		return x.FifteenMinLoad
	}
	return 0
}

func (x *Load) GetProcTotal() int32 {
	if x != nil {
		return x.ProcTotal
	}
	return 0
}

func (x *Load) GetProcRunning() int32 {
	if x != nil {
		return x.ProcRunning
	}
	return 0
}

func (x *Load) GetProcBlocked() int32 {
	if x != nil {
		return x.ProcBlocked
	}
	return 0
}

type Memory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMem  uint64 `protobuf:"varint,1,opt,name=totalMem,proto3" json:"totalMem,omitempty"`
	FreeMem   uint64 `protobuf:"varint,2,opt,name=freeMem,proto3" json:"freeMem,omitempty"`
	TotalSwap uint64 `protobuf:"varint,3,opt,name=totalSwap,proto3" json:"totalSwap,omitempty"`
	FreeSwap  uint64 `protobuf:"varint,4,opt,name=freeSwap,proto3" json:"freeSwap,omitempty"`
}

func (x *Memory) Reset() {
	*x = Memory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_machine_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_machine_status_proto_rawDescGZIP(), []int{2}
}

func (x *Memory) GetTotalMem() uint64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *Memory) GetFreeMem() uint64 {
	if x != nil {
		return x.FreeMem
	}
	return 0
}

func (x *Memory) GetTotalSwap() uint64 {
	if x != nil {
		return x.TotalSwap
	}
	return 0
}

func (x *Memory) GetFreeSwap() uint64 {
	if x != nil {
		return x.FreeSwap
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskName  string `protobuf:"bytes,1,opt,name=diskName,proto3" json:"diskName,omitempty"`
	TotalInGb int32  `protobuf:"varint,2,opt,name=totalInGb,proto3" json:"totalInGb,omitempty"`
	FreeInGb  int32  `protobuf:"varint,3,opt,name=freeInGb,proto3" json:"freeInGb,omitempty"`
}

func (x *Disk) Reset() {
	*x = Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_machine_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_machine_status_proto_rawDescGZIP(), []int{3}
}

func (x *Disk) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *Disk) GetTotalInGb() int32 {
	if x != nil {
		return x.TotalInGb
	}
	return 0
}

func (x *Disk) GetFreeInGb() int32 {
	if x != nil {
		return x.FreeInGb
	}
	return 0
}

type Docker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running     int32  `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Stopped     int32  `protobuf:"varint,2,opt,name=stopped,proto3" json:"stopped,omitempty"`
	MemoryUsage uint64 `protobuf:"varint,3,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
}

func (x *Docker) Reset() {
	*x = Docker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_status_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docker) ProtoMessage() {}

func (x *Docker) ProtoReflect() protoreflect.Message {
	mi := &file_machine_status_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docker.ProtoReflect.Descriptor instead.
func (*Docker) Descriptor() ([]byte, []int) {
	return file_machine_status_proto_rawDescGZIP(), []int{4}
}

func (x *Docker) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *Docker) GetStopped() int32 {
	if x != nil {
		return x.Stopped
	}
	return 0
}

func (x *Docker) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

var File_machine_status_proto protoreflect.FileDescriptor

var file_machine_status_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x06,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x0a,
	0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x69,
	0x73, 0x6b, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x22, 0xd2, 0x01, 0x0a, 0x04, 0x4c, 0x6f, 0x61,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x6e, 0x4c, 0x6f, 0x61,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x4c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x66, 0x69, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x4c,
	0x6f, 0x61, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x4d, 0x69,
	0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x66, 0x69, 0x66,
	0x74, 0x65, 0x65, 0x6e, 0x4d, 0x69, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x63, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x63, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x63, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x78, 0x0a,
	0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x4d, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x4d, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x65, 0x6d, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x77, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x77, 0x61, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x72, 0x65, 0x65, 0x53, 0x77, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66,
	0x72, 0x65, 0x65, 0x53, 0x77, 0x61, 0x70, 0x22, 0x5c, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x47, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x47, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x65,
	0x65, 0x49, 0x6e, 0x47, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x65,
	0x65, 0x49, 0x6e, 0x47, 0x62, 0x22, 0x5e, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x70,
	0x70, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_machine_status_proto_rawDescOnce sync.Once
	file_machine_status_proto_rawDescData = file_machine_status_proto_rawDesc
)

func file_machine_status_proto_rawDescGZIP() []byte {
	file_machine_status_proto_rawDescOnce.Do(func() {
		file_machine_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_machine_status_proto_rawDescData)
	})
	return file_machine_status_proto_rawDescData
}

var file_machine_status_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_machine_status_proto_goTypes = []interface{}{
	(*MachineStatus)(nil), // 0: MachineStatus
	(*Load)(nil),          // 1: Load
	(*Memory)(nil),        // 2: Memory
	(*Disk)(nil),          // 3: Disk
	(*Docker)(nil),        // 4: Docker
}
var file_machine_status_proto_depIdxs = []int32{
	1, // 0: MachineStatus.load:type_name -> Load
	2, // 1: MachineStatus.memory:type_name -> Memory
	4, // 2: MachineStatus.docker:type_name -> Docker
	3, // 3: MachineStatus.disk:type_name -> Disk
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_machine_status_proto_init() }
func file_machine_status_proto_init() {
	if File_machine_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_machine_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Load); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_status_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Docker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machine_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machine_status_proto_goTypes,
		DependencyIndexes: file_machine_status_proto_depIdxs,
		MessageInfos:      file_machine_status_proto_msgTypes,
	}.Build()
	File_machine_status_proto = out.File
	file_machine_status_proto_rawDesc = nil
	file_machine_status_proto_goTypes = nil
	file_machine_status_proto_depIdxs = nil
}
